### PR TITLE
fixes unordered lists, h1-h6 formatting

### LINKED ISSUE #12: minor formatting problems with unordered lists and headings
I had some minor formatting problems when converting large batches of files. Input like:

```html
<h3>I'm an h3:</h3>
<ul>
  <li>li_1</li>
  <li>li_2</li>
  <li>li_3</li>
</ul>
```

would result in markdown like:

```md
###I'm an h3:

*li_1
*li_2
*li_3
```

The problem was just some the lack of spaces.

Here's the MD that *should* be built:

```md
### I'm an h3:
* li_1
* li_2
* li_3
```

### PR DESCRIPTION
**Pull request by josh-works**
closes #12

Unfortunately, this *seems* like a more intrusive PR than I intended it to be - it may be a character encoding thing, but my editor removed some white space from a few of the files, and those are showing up in the diffs.

The core of this commit is in `lib/html2markdown/converter.rb` and the last two tests in `spec/cases/html_page_spec.rb`

The changes I am proposing are tested, and all rspec tests are green.

note: I followed the rspec deprecation guidelines to allow it to play well with `should` usage, with:

https://github.com/29decibel/html2markdown/compare/master...josh-works:master?expand=1#diff-93830fa29d616f7c87903d08b5b1b29aR13

### CODE REVIEW

File: lib/html2markdown/converter.rb [hunk 1]
```diff
@@ -51,11 +51,17 @@ def wrap_node(node,contents=nil)
...
+        result << "## #{contents}\n"
       when 'h3'
-        result << "####{contents}\n"
+        result << "### #{contents}\n"
+      when 'h4'
+        result << "#### #{contents}\n"
+      when 'h5'
+        result << "##### #{contents}\n"
+      when 'h6'
+        result << "###### #{contents}\n"
```
Comment (josh-works) [inline lib/html2markdown/converter.rb]: I added handling for h4-h6, since that's standard markdown formatting, and just added a space between the heading markers and the heading content, and did the same with `li`'s

File: spec/cases/html_page_spec.rb [hunk 2]
```diff
@@ -46,15 +46,15 @@
 <font face="微软雅黑 "><font size="3"><strong>DIY的手绘行程图</strong></font></font><br>
 <span style="position: absolute; display: none" id="attach_1254048" onmouseover="showMenu({'ctrlid':this.id,'pos':'13'})"><img src="images/go2eu/attachimg.gif" border="0"></span>
 <img src="http://att.qyer.com/day_111228/1112282241c0deb3a69dcd9cf5.jpg" file="http://att.qyer.com/day_111228/1112282241c0deb3a69dcd9cf5.jpg" width="700" class="zoom" onclick="zoom(this, this.src)" id="aimg_1254048" onmouseover="showMenu({'ctrlid':this.id,'pos':'12'})" alt="55105222201110032253301023057594630_006.jpg">
-<div class="t_attach" id="aimg_1254048_menu" style="position: absolute; display: none">				
+<div class="t_attach" id="aimg_1254048_menu" style="position: absolute; display: none">
```
Comment (josh-works) [inline spec/cases/html_page_spec.rb]: my editor stripped whitespace. Sorry! If you'd like me to unstage these commits or anything so it's not impacted, just let me know.

File: spec/cases/html_page_spec.rb [hunk 3]
```diff
@@ -68,9 +68,9 @@
       if node['src'].end_with? 'gif'
         ''
       elsif node['src'].start_with? 'http'
-        "![#{node['alt']}](#{node['src']} =300x)" 
+        "![#{node['alt']}](#{node['src']} =300x)"
       else
-        "![#{node['alt']}](http://bbs.qyer.com/#{node['src']} =300x)" 
+        "![#{node['alt']}](http://bbs.qyer.com/#{node['src']} =300x)"
```
Comment (josh-works) [inline spec/cases/html_page_spec.rb]: more whitespace stripping.

File: spec/cases/html_page_spec.rb [hunk 4]
```diff
@@ -95,4 +95,17 @@
...
+  end
+
+  it 'converts headers like you do' do
+    HTMLPage.new(contents: '<h1>heading 1</h1>').markdown.should == "# heading 1"
+    HTMLPage.new(contents: '<h2>heading 2</h2>').markdown.should == "## heading 2"
+    HTMLPage.new(contents: '<h3>heading 3</h3>').markdown.should == "### heading 3"
+    HTMLPage.new(contents: '<h4>heading 4</h4>').markdown.should == "#### heading 4"
+    HTMLPage.new(contents: '<h5>heading 5</h5>').markdown.should == "##### heading 5"
+    HTMLPage.new(contents: '<h6>heading 6</h6>').markdown.should == "###### heading 6"
+  end
```
Comment (josh-works) [inline spec/cases/html_page_spec.rb]: verbose but comprehensive tests.

File: spec/spec_helper.rb [hunk 5]
```diff
@@ -9,8 +9,8 @@
 # configuration for rspec
 RSpec.configure do |config|
   config.mock_with :rspec
-  config.color_enabled = true
-
+  config.color = true
+  config.expect_with(:rspec) { |c| c.syntax = :should }
```
Comment (josh-works) [inline spec/spec_helper.rb]: this line fixes some rspec deprecation warnings.

**Comment by 29decibel** [comment]
Thanks @josh-works !
